name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
    # 'swift test' fails due to resource bundle bug: https://bugs.swift.org/browse/SR-13560
      run: xcodebuild -scheme PtFormatObjC-Package -destination platform=macOS test
